JovemProgramadorWeb/Models/Aluno.cs
namespace JovemProgramadorWeb.Models
{
    public class Aluno
    {
        public int id { get; set; }
        public string nome { get; set; }
        public double nota { get; set; }
        public string situacao { get; set; }
        public string cep { get; set; }
    }
}

JovemProgramadorWeb/Models/Endereco.cs
namespace JovemProgramadorWeb.Models
{
    public class Endereco
    {
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
        public string ddd { get; set; }
    }
}

JovemProgramadorWeb/Models/ErrorViewModel.cs
namespace JovemProgramadorWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JovemProgramadorWeb/Controllers/AlunoController.cs
using JovemProgramadorWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using JovemProgramadorWeb.Data.Repositorio.Interface;

namespace JovemProgramadorWeb.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IAlunoRepositorio _alunoRepositorio;

        public AlunoController(IConfiguration configuration, IAlunoRepositorio alunoRepositorio) 
        {
            _configuration = configuration;
            _alunoRepositorio = alunoRepositorio;
        }

        public IActionResult Aluno() 
        { 
            var aluno = _alunoRepositorio.BuscarAlunos();
            return View(aluno);
        }
        #region Adicionar Aluno
        public IActionResult AdicionarAluno()
        {
            return View();
        }

        public IActionResult InserirAluno(Aluno aluno)
        {
            try
            {
                _alunoRepositorio.InserirAluno(aluno);
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro ao inserir aluno";
            }

            TempData["MsgSucesso"] = "Aluno adicionado com sucesso!";
            return RedirectToAction("Aluno");

        }
        #endregion

        #region Atualizar Dados
        public IActionResult EditarAluno(int id)
        {
            var idAluno = _alunoRepositorio.BuscarId(id);
            return View("EditarAluno", idAluno);
        }

        public IActionResult AtualizarDadosAluno(Aluno aluno)
        {
            try
            {
                _alunoRepositorio.AtualizarDadosAluno(aluno);
            }catch (Exception ex)
            {

            }
            return RedirectToAction("Aluno");
        }
        #endregion

        public IActionResult ExcluirAluno(Aluno aluno)
        {
            _alunoRepositorio.ExcluirAluno(aluno);
            return RedirectToAction("Aluno");
        }


        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            Endereco endereco = new Endereco();

            try 
            {
                cep = cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"]+ cep + "/json");
                if (result.IsSuccessStatusCode)
                {
                    endereco = JsonSerializer.Deserialize<Endereco>(await result.Content.ReadAsStringAsync(), new JsonSerializerOptions());
                    
                }
                else
                {
                    ViewData["MsgErro"] = "Erro na busca do endereço!";
                }
            } 
            catch (Exception ex) 
            { 
                throw; 
            }
            ViewData["MsgSucesso"] = "Busca feita com sucesso!";
            return View("Endereco", endereco);
        }
    }
}

JovemProgramadorWeb/Controllers/HomeController.cs
using JovemProgramadorWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JovemProgramadorWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JovemProgramadorWeb/Controllers/LoginController.cs
using JovemProgramadorWeb.Data;
using JovemProgramadorWeb.Data.Repositorio.Interface;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        private readonly BancoContexto _bancoContexto;
        public LoginController(IAlunoRepositorio alunoRepositorio, BancoContexto bancoContexto)
        {
            _alunoRepositorio = alunoRepositorio;
            _bancoContexto = bancoContexto;
        }
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Logar(string nome, string cep)
        {
            var usuario = _alunoRepositorio.Logar(nome, cep);
            if (usuario == true) 
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["MsgErro"] = "Nome ou CEP inválidos!";
            return View("Login");
        }

    }
}

JovemProgramadorWeb/Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Mvc;
namespace JovemProgramadorWeb.Controllers
{
    public class ProfessorController : Controller
    {
        public IActionResult Professor()
        {
            return View();
        }
    }
}

JovemProgramadorWeb/Views/Aluno/AdicionarAluno.cshtml
@model Aluno;
<style>
    .Tudo{
        display : flex;
        flex-direction:column;
        justify-content : center;
        width : 100%;
    }
    .form{
        width: 30%;
        align-self: center;

    }
    .formFilho{
        padding-top: 1%;
        padding-bottom: 1%;
    }
    .botao {
        align-self: center;

    }
</style>
<h1 class="text-center">Adicionar</h1>
<br />
<div class="Tudo">
    <form asp-controller="Aluno" asp-action="InserirAluno" method="post">
        <div class="formFilho form-floating">
            <input type="text" asp-for="nome" class=" form-control" id="floatingInputGrid" placeholder="nome">
            <label for="floatingInputGrid">Nome :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="nota" class="form-control" id="floatingInputGrid" placeholder="nota">
            <label for="floatingInputGrid">Nota :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="situacao" class="form-control" id="floatingInputGrid" placeholder="situacao">
            <label for="floatingInputGrid">Situação :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="cep" class="form-control" id="floatingInputGrid" placeholder="nome">
            <label for="floatingInputGrid">CEP :</label>
        </div>
        
    </form>
    <br />
    <div class="botao">
        <a class="btn btn-primary" role="button" asp-area="" asp-controller="Aluno" asp-action="Aluno"> Voltar</a>
        <button type="submit" class="btn btn-primary" role="button"> Cadastrar</button>
    </div>
</div>

JovemProgramadorWeb/Views/Aluno/Aluno.cshtml
@model List<Aluno>

@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@if (ViewData["MsgSucesso"] != null)
{
    <div class="alert-success">
        @ViewData["MsgSucesso"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Alunos</th>
            <th scope="col">Nota</th>
            <th scope="col">Situação</th>
            <th scope="col">CEP</th>
            <th scope="col">Endereço</th>
            <th scope="col">Editar</th>
            <th scope="col">Excluir</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>
                        @aluno.id
                    </td>
                    <td>
                        @aluno.nome
                    </td>
                    <td>
                        @aluno.nota
                    </td>
                    <td>
                        @aluno.situacao
                    </td>
                    <td>
                        @aluno.cep
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Aluno" asp-action="BuscarEndereco" asp-route-cep="@aluno.cep">Endereço</a>
                        </div>
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Aluno" asp-action="EditarAluno" asp-route-id="@aluno.id">Editar</a>
                        </div>
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Aluno" asp-action="ExcluirAluno" asp-route-id="@aluno.id">Excluir</a>
                        </div>
                    </td>
                </tr>
            }  
        }

    </tbody>
</table>
<div class="text-center">
    <a type="submit" class="btn btn-primary" role="button" asp-area="" asp-controller="Aluno" asp-action="AdicionarAluno" > Adicionar</a>
</div>

JovemProgramadorWeb/Views/Aluno/EditarAluno.cshtml
@model Aluno;
<style>
    .Tudo {
        display: flex;
        flex-direction: column;
        justify-content: center;
        width: 100%;
    }

    .form {
        width: 30%;
        align-self: center;
    }

    .formFilho {
        padding-top: 1%;
        padding-bottom: 1%;
    }

    .botao {
        display: flex;
        justify-content: center;
        column-gap: 1%;
    }
</style>

<h1 class="text-center">Editar</h1>
<br />
<div class="Tudo">
    <form asp-controller="Aluno" asp-action="AtualizarDadosAluno" asp-route-id="@Model.id" class="form" method="put">
        <div class="formFilho form-floating">
            <input type="text" asp-for="nome" class=" form-control" id="floatingInputGrid" placeholder="nome">
            <label for="floatingInputGrid">Nome :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="nota" class="form-control" id="floatingInputGrid" placeholder="nota">
            <label for="floatingInputGrid">Nota :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="situacao" class="form-control" id="floatingInputGrid" placeholder="situacao">
            <label for="floatingInputGrid">Situação :</label>
        </div>
        <div class="formFilho form-floating">
            <input type="text" asp-for="cep" class="form-control" id="floatingInputGrid" placeholder="nome">
            <label for="floatingInputGrid">CEP :</label>
        </div>

        <br />
        <div class="botao">
            <a class="btn btn-primary" role="button" asp-area="" asp-controller="Aluno" asp-action="Aluno"> Voltar</a>
            <button type="submit" class="btn btn-primary" role="button"> Editar</button>
        </div>
    </form>
</div>

JovemProgramadorWeb/Views/Aluno/Endereco.cshtml
@model Endereco



<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Logradouro: @Html.DisplayFor(endereco => endereco.logradouro)</p>
                <p>Localidade: @Html.DisplayFor(endereco => endereco.localidade)</p>
                <p>Bairro: @Html.DisplayFor(endereco => endereco.bairro)</p>
                <p>UF: @Html.DisplayFor(endereco => endereco.uf)</p>
                <p>DDD: @Html.DisplayFor(endereco => endereco.ddd)</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Aluno">Fechar</a>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    <script>
        $(document).ready(function () {
            $('#myModal').modal('show');
        });
    </script>
}

JovemProgramadorWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    h1,p{
        color: #000000
    }
</style>
<div class="text-center">
    <h1 class="display-4 ">|EU QUERO UM TRABALHO|</h1>
    <p>Quer um emprego ? <a href="https://br.linkedin.com/">Clique aqui</a>.</p>
</div>
<div class="text-center">
    <h2>
        Sem ideias criativas para colocar aqui!

    </h2>
</div>
<div class="text-center">
    <img src="~/imagem/teste.jpg" class="img-fluid " alt="...">
</div>

JovemProgramadorWeb/Views/Login/Login.cshtml
@model Aluno;
@{
    Layout = "_LayoutDeslogado";
}
@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}

<style>
    .formLogin {
        padding-top: 20% ;
        display: flex;
        flex-direction: column;
        text-align: center;
    }
    .row {
        width: 20%;
        align-self: center;
    }
    .btn {
        width : 10%;
        display: flex;
        align-self: center;
        justify-content: center;
        column-gap: 1%;
    }
    }
</style>

<form class="formLogin" asp-controller="Login" asp-action="Logar">
    <h1>Login</h1>
    <div class="row mb-3">
        <label for="nome" class="col-sm-2 col-form-label">Nome</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="nome" asp-for="nome">
        </div>
    </div>
    <div class="row mb-3">
        <label for="cep" class="col-sm-2 col-form-label">CEP</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="cep"asp-for="cep">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Logar</button>
</form>

JovemProgramadorWeb/Views/Professor/Professor.cshtml
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Professor</th>
            <th scope="col">Disciplina</th>
            <th scope="col">Nivel de satisfação</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Nivaldo</td>
            <td>Banco de Dados</td>
            <td>10.0</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Kátia</td>
            <td>Desenvolvimento Web</td>
            <td>10.0</td>
        </tr>
    </tbody>
</table>

JovemProgramadorWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JovemProgramadorWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JovemProgramadorWeb.styles.css" asp-append-version="true" />
</head>
<body >
    <style>
        body {
            background-color: #B0C4DE;
        }

    </style>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-body border-bottom box-shadow mb-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list text-white" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
            </svg>
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">JovemProgramadorWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Aluno" asp-action="Aluno">Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Professor" asp-action="Professor">Professor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-black">
        <div class="container">
            &copy; 2023 - JovemProgramadorWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JovemProgramadorWeb/Views/Shared/_LayoutDeslogado.cshtml
<style>
    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 60px;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JovemProgramadorWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JovemProgramadorWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <style>
        body {
            background-color: #B0C4DE;
        }

    </style>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-body border-bottom box-shadow mb-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list text-white" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
            </svg>
            <div class="container-fluid">
                <a class="navbar-brand text-white">JovemProgramadorWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-bottom footer text-black">
        <div class="container">
            &copy; 2023 - JovemProgramadorWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>